"""Item 0: anchors (a), (b) and the generator packet (c). Exact arithmetic only."""
import json
import pathlib
import sympy as sp
from sympy.physics.quantum.cg import CG as SymCG
from audit_field import Q1, Q2, QONE, closure, R5, Quat
from audit_su2lib import theta, basis, cg, ms

HERE = pathlib.Path(__file__).parent
res = {}

# (a) Theta v_2 with global phase +1: Theta v_m = (-1)^m v_{-m}
th = theta(basis(2))
res["0a_Theta_v2_coeffs_m=-3..3"] = [str(x) for x in th]
assert th == basis(-2), th
# cross-check general-spin form with eps_3 = -1 reproduces section 2.2 on all v_m
for m in range(-3, 4):
    assert theta(basis(m)) == [sp.Integer(-1) ** abs(m) * x for x in basis(-m)]

# (b) <3 3; 3 -3 | 6 0>
b_racah = cg(3, 3, 3, -3, 6, 0)
b_sympy = sp.nsimplify(SymCG(3, 3, 3, -3, 6, 0).doit())
b_closed = sp.sqrt(sp.factorial(6) * sp.factorial(6) / sp.factorial(12))
assert sp.simplify(b_racah - b_sympy) == 0 and sp.simplify(b_racah - b_closed) == 0
res["0b_CG_33_3m3_60"] = str(b_racah)
res["0b_CG_squared"] = str(sp.nsimplify(b_racah ** 2))
# cross-check my Racah CG against sympy on all 3x3 couplings
bad = 0
for J in range(0, 7):
    for m1 in range(-3, 4):
        for m2 in range(-3, 4):
            M = m1 + m2
            if abs(M) > J:
                continue
            a = cg(3, m1, 3, m2, J, M)
            s = SymCG(3, m1, 3, m2, J, M).doit()
            if sp.simplify(a - s) != 0:
                bad += 1
res["0b_racah_vs_sympy_mismatches_3x3"] = bad
assert bad == 0

# (c) generator packet
n1, n2 = Q1.norm2(), Q2.norm2()
res["0c_norm2_q1"] = str(n1)
res["0c_norm2_q2"] = str(n2)
assert n1 == R5(1) and n2 == R5(1)
G = closure([Q1, Q2])
res["0c_order"] = len(G)
# group check: closed under inverse (conj for unit quaternions)
Gs = set(G)
assert all(g.conj() in Gs for g in G)
# orders of generators
def order(q):
    p, k = q, 1
    while p != QONE:
        p, k = p * q, k + 1
    return k
res["0c_order_q1"] = order(Q1)
res["0c_order_q2"] = order(Q2)
# derived subgroup: generated by all commutators
comms = {a * b * a.conj() * b.conj() for a in G for b in G}
D = closure(list(comms))
res["0c_number_of_distinct_commutators"] = len(comms)
res["0c_derived_subgroup_order"] = len(D)
res["0c_perfect"] = (len(D) == len(G))
# element-order histogram and centre, recorded for later cross-checks
from collections import Counter
res["0c_element_order_histogram"] = dict(sorted(Counter(order(g) for g in G).items()))
centre = [g for g in G if all(g * h == h * g for h in G)]
res["0c_centre_order"] = len(centre)
# homomorphism check of the su2 map on all pairs of a sample
from audit_field import mat_mul
for a in G[:30]:
    for b in G[:30]:
        A, B, C = a.su2(), b.su2(), (a * b).su2()
        assert mat_mul(A, B) == C
res["0c_su2_map_homomorphism_checked_pairs"] = 900

(HERE / "audit_res_item0.json").write_text(json.dumps(res, indent=1))
print(json.dumps(res, indent=1))
