# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username if you set one up
open_collective: openwave
# ko_fi: # Replace with your Ko-fi username
# patreon: # Replace with your Patreon username
# custom: # Add custom funding URLs if needed
