"""Items 10, 11, 12, 16 (+ Frobenius-Schur indicators used by item 21).

Everything about Gamma is derived from the two generators q1, q2 of handout Section 2.4:
the group is generated by closure (exact arithmetic in Q(sqrt5)), conjugacy classes by
conjugation, characters of V_j by the Chebyshev recurrence in the real part w of each element,
isotypic projectors as spectral projectors of a generic combination of class-sum operators.
"""
import random

import sympy as sp

from solver_lib import (Q1, Q2, Q5, QC, ONE, generate_group, conjugacy_classes, D_mono,
                        qc_rank, qc_minpoly, qc_eye, fact_weight, transform, norm2, mvals,
                        save_results, s)

G = generate_group([Q1, Q2])
assert len(G) == 120
classes = conjugacy_classes(G)
cls_of = {}
for ci, C in enumerate(classes):
    for g in C:
        cls_of[g] = ci


def order_of(q):
    k, p = 1, q
    while p != ONE:
        p = p * q
        k += 1
    return k


class_info = []
for ci, C in enumerate(classes):
    g = C[0]
    class_info.append({"size": len(C), "order": order_of(g), "trace_2w": s((2 * g.w).to_sympy())})
print("classes:", [(c["size"], c["order"], c["trace_2w"]) for c in class_info])

out = {"classes": class_info}


# ------------------------------------------------------------------ item 10: invariants
def chi_spin(n, w):
    """Character of V_{n/2} at an element with real part w: Chebyshev U_n(w)."""
    U0, U1 = Q5(1), 2 * w
    if n == 0:
        return U0
    for _ in range(n - 1):
        U0, U1 = U1, 2 * w * U1 - U0
    return U1


def dim_inv(n):
    tot = Q5(0)
    for C in classes:
        tot = tot + len(C) * chi_spin(n, C[0].w)
    tot = tot / 120
    assert tot.b == 0 and tot.a.denominator == 1
    return int(tot.a)


inv10 = {K: dim_inv(2 * K) for K in range(0, 7)}
print("item 10: dim V_K^Gamma, K=0..6:", inv10)
# independent cross-check using only the generators: nullity of [D(q1)-I ; D(q2)-I]
null10 = {}
for K in range(0, 7):
    n = 2 * K
    D1, D2 = D_mono(Q1.su2(), n), D_mono(Q2.su2(), n)
    I = qc_eye(n + 1)
    rows = [[D1[i][k] - I[i][k] for k in range(n + 1)] for i in range(n + 1)] + \
           [[D2[i][k] - I[i][k] for k in range(n + 1)] for i in range(n + 1)]
    null10[K] = (n + 1) - qc_rank(rows)
print("         nullspace cross-check:", null10)
beyond = {K: dim_inv(2 * K) for K in range(7, 31)}
half = {f"{n}/2": dim_inv(n) for n in range(1, 31, 2)}
print("         beyond K=6 (K=7..30):", beyond)
print("         half-integer spins 1/2..29/2:", half)
out["item10"] = {"dim_VK_Gamma_K0_6": {str(k): v for k, v in inv10.items()},
                 "nullspace_crosscheck_K0_6": {str(k): v for k, v in null10.items()},
                 "EXTRA_beyond_K6_K7_30": {str(k): v for k, v in beyond.items()},
                 "EXTRA_half_integer_spins": half}


# ------------------------------------------------------------------ decomposition machinery
def qc_to_sym(M):
    return sp.Matrix(len(M), len(M[0]), lambda i, k: M[i][k].to_sympy())


def to_orth(Pm, n):
    return sp.Matrix(n + 1, n + 1, lambda ap, a: Pm[ap, a] * sp.sqrt(fact_weight(n, ap) / fact_weight(n, a)))


def exact_simplify(e):
    e = sp.nsimplify(sp.radsimp(sp.expand(e)), rational=False) if False else sp.radsimp(sp.expand(e))
    return sp.simplify(e)


def decompose(n, seed=12345):
    """Isotypic decomposition of V_{n/2} restricted to Gamma."""
    Zc = []
    for C in classes:
        acc = [[QC(0)] * (n + 1) for _ in range(n + 1)]
        for g in C:
            D = D_mono(g.su2(), n)
            acc = [[acc[i][k] + D[i][k] for k in range(n + 1)] for i in range(n + 1)]
        Zc.append(acc)
    rnd = random.Random(seed)
    coeffs = [rnd.randint(-7, 7) for _ in classes]
    Z = [[sum((c * Zc[t][i][k] for t, c in enumerate(coeffs)), QC(0)) for k in range(n + 1)]
         for i in range(n + 1)]
    mp = qc_minpoly(Z)
    lam = sp.symbols("lam")
    poly = sum(c.to_sympy() * lam ** i for i, c in enumerate(mp))
    rts = sp.roots(sp.Poly(sp.expand(poly), lam))
    assert sum(rts.values()) == len(mp) - 1 and all(m == 1 for m in rts.values()), rts
    roots = [sp.radsimp(r) for r in rts]
    Zs = qc_to_sym(Z)
    Zcs = [qc_to_sym(M) for M in Zc]
    Id = sp.eye(n + 1)
    comps = []
    for i, li in enumerate(roots):
        P = Id
        for k, lk in enumerate(roots):
            if k != i:
                P = P * (Zs - lk * Id) / (li - lk)
        P = P.applyfunc(lambda e: sp.radsimp(sp.expand(e)))
        # checks in the monomial basis
        assert (P * P - P).applyfunc(lambda e: sp.simplify(e)) == sp.zeros(n + 1), "idempotent"
        d = sp.simplify(P.trace())
        # each class sum acts as a scalar on the image
        chi = []
        for t, C in enumerate(classes):
            ZP = Zcs[t] * P
            mu = sp.simplify((ZP).trace() / d)
            assert (ZP - mu * P).applyfunc(lambda e: sp.simplify(e)) == sp.zeros(n + 1), "central"
            chi.append(sp.simplify(sp.radsimp((Zcs[t] * P).trace() / len(C))))
        normchi = sp.simplify(sum(len(C) * chi[t] * sp.conjugate(chi[t])
                                  for t, C in enumerate(classes)) / 120)
        # character-formula projector reproduces P  (P' = (d_sigma/|G|) sum conj(chi) Z_C), with
        # d_sigma = d / m and m^2 = <chi,chi>
        m = sp.sqrt(normchi)
        dsig = d / m
        Pchar = sum((sp.conjugate(chi[t]) * Zcs[t] for t in range(len(classes))),
                    sp.zeros(n + 1)) * dsig / 120
        char_ok = (Pchar - P).applyfunc(lambda e: sp.simplify(e)) == sp.zeros(n + 1)
        Po = to_orth(P, n).applyfunc(lambda e: sp.radsimp(sp.expand(e)))
        herm = (Po - Po.H).applyfunc(lambda e: sp.simplify(e)) == sp.zeros(n + 1)
        D1o = to_orth(qc_to_sym(D_mono(Q1.su2(), n)), n)
        D2o = to_orth(qc_to_sym(D_mono(Q2.su2(), n)), n)
        comm = all((Do * Po - Po * Do).applyfunc(lambda e: sp.simplify(e)) == sp.zeros(n + 1)
                   for Do in (D1o, D2o))
        # Frobenius-Schur indicator of the constituent (valid when m = 1)
        fs = sp.simplify(sum(chi[cls_of[g * g]] for g in G) / 120) if m == 1 else None
        comps.append({"eigenvalue_of_random_class_combination": li, "rank": d, "chi": chi,
                      "norm_chi": normchi, "multiplicity": m, "irrep_dim": dsig,
                      "P_mono": P, "P_orth": Po, "hermitian": herm, "commutes_with_D": comm,
                      "character_projector_matches": char_ok, "FS": fs})
    chiV = [sum(c["chi"][t] for c in comps) for t in range(len(classes))]
    normV = sp.simplify(sum(len(C) * chiV[t] * sp.conjugate(chiV[t])
                            for t, C in enumerate(classes)) / 120)
    return comps, normV, coeffs


# ------------------------------------------------------------------ item 11 + 12 (level 6)
comps6, normV3, coeffs = decompose(6)
print("item 11: <chi_V3, chi_V3> =", normV3, " number of isotypic components:", len(comps6))
item11 = {"inner_product_chi_V3": s(normV3), "number_of_isotypic_components": len(comps6),
          "random_class_coefficients": coeffs, "components": []}
item12 = {}
for c in comps6:
    print(f"   component: rank {c['rank']}, <chi,chi> = {c['norm_chi']}, multiplicity {c['multiplicity']},"
          f" irrep dim {c['irrep_dim']}, FS = {c['FS']}, hermitian {c['hermitian']}, commutes "
          f"{c['commutes_with_D']}, char-projector match {c['character_projector_matches']}")
    print("      character on classes:", c["chi"])
    item11["components"].append({"rank": s(c["rank"]), "inner_product_chi": s(c["norm_chi"]),
                                 "multiplicity": s(c["multiplicity"]), "irrep_dim": s(c["irrep_dim"]),
                                 "character_on_classes": [s(x) for x in c["chi"]],
                                 "Frobenius_Schur_indicator": s(c["FS"])})
    norms = []
    for K in range(7):
        X = transform(c["P_orth"], K)
        nv = sp.simplify(sp.radsimp(norm2(X)))
        norms.append(nv)
    print("      ||M_K(P)||^2, K=0..6:", norms, " float:", [float(x) for x in norms])
    key = f"d={c['rank']}"
    item12[key] = {"norm2_MK_P_K0_6": [s(x) for x in norms],
                   "minimal_polynomials": [s(sp.minimal_polynomial(x, sp.Symbol('X'))) for x in norms],
                   "float_crosscheck": [float(x) for x in norms],
                   "construction": "spectral projector of a random integer combination of class-sum "
                                   "operators (Lagrange interpolation in the exact minimal polynomial); "
                                   "checked idempotent, Hermitian, Gamma-commuting, equal to the "
                                   "character-formula projector (d/|G|) sum conj(chi(g)) D(g)",
                   "P_orth_rows": [[s(e) for e in c["P_orth"].row(i)] for i in range(7)],
                   "checks": {"hermitian": c["hermitian"], "commutes_with_D_q1_q2": c["commutes_with_D"],
                              "character_projector_matches": c["character_projector_matches"]}}
out["item11"] = item11
out["item12"] = item12

# ------------------------------------------------------------------ item 16 (levels 1..6)
item16 = {}
rnd = random.Random(7)
for n in range(1, 7):
    j = sp.Rational(n, 2)
    comps, normV, _ = decompose(n)
    eps = -1 if n == 6 else 1
    # which ranks can rho^{(j)}_K carry: test a sample state (exact rational complex)
    u = sp.Matrix([sp.Rational(rnd.randint(-9, 9), rnd.randint(1, 5)) + sp.I * rnd.randint(-9, 9)
                   for _ in range(n + 1)])
    carried = [K for K in range(0, n + 1)
               if any(sp.simplify(x) != 0 for x in transform(u * u.H, K, j, eps))]
    lev = {"j": s(j), "inner_product_chi": s(normV), "sample_state_ranks_nonzero": carried,
           "components": []}
    for c in comps:
        nrm = [sp.simplify(sp.radsimp(norm2(transform(c["P_orth"], K, j, eps)))) for K in range(0, n + 1)]
        nz = [K for K, v in enumerate(nrm) if v != 0]
        lev["components"].append({"rank": s(c["rank"]), "multiplicity": s(c["multiplicity"]),
                                  "irrep_dim": s(c["irrep_dim"]), "FS": s(c["FS"]),
                                  "norm2_MjK_P_K0_2j": [s(x) for x in nrm],
                                  "nonzero_ranks": nz})
        print(f"item 16: level {n} (j={j}): comp rank {c['rank']} mult {c['multiplicity']} FS {c['FS']}:"
              f" ||M^(j)_K(P)||^2 = {nrm}")
    print(f"         level {n}: sample-state ranks carried by rho^(j)_K: {carried}")
    item16[f"level_{n}"] = lev
out["item16"] = item16
save_results("group", out)
